# docker-compose-local.yml
version: '3.8'

services:
  # Multi-Agent Application - LOCAL LOGGING ONLY
  multi-agent-local:
    build: .
    container_name: multi-agent-local
    environment:
      # Azure OpenAI Configuration
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      
      # Local logging only - no external endpoints
      - LOG_LEVEL=INFO
      - LOCAL_LOGGING_ONLY=true
    volumes:
      # Mount local directory to save logs
      - ./logs:/app/logs
      - ./local_traces:/app/traces
    command: python local_main.py
    
  # Optional: Local Jaeger for visualization (still local, no external calls)
  jaeger-local:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-local
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory  # In-memory storage only
    volumes:
      - ./jaeger_data:/tmp  # Local storage
    
  # Optional: Local file-based trace collector
  file-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: file-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./local-otel-config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - ./trace_files:/traces  # Save traces to local files
      - ./logs:/logs
    ports:
      - "4317:4317"   # OTLP gRPC (for local apps)
      - "4318:4318"   # OTLP HTTP (for local apps)
      - "8888:8888"   # Health check

volumes:
  logs:
  traces:
  jaeger_data: