# local-otel-config.yaml
# Corrected configuration for OpenTelemetry Collector

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 100

exporters:
  # The 'debug' exporter uses 'verbosity' instead of 'loglevel'
  debug:
    verbosity: detailed

  # File exporters for saving data locally
  file:
    path: /traces/traces.json
    format: json
  
  file/metrics:
    path: /logs/metrics.json
    format: json
  
  file/logs:
    path: /logs/logs.json
    format: json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, debug]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/metrics, debug]
    
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/logs, debug]
